#
# Module manifest for module 'ShoutOut'
#
# Generated by: Joakim Olsson
#
# Generated on: 2019-03-26
#

@{
    RootModule = '.\ShoutOut.psm1'
    ModuleVersion = '1.0.2'
    GUID = '3f16ec91-ba22-47a9-8099-25807e68e88b'
    Author = 'Joakim Olsson'
    CompanyName = 'Addskills Cornerstone Group AB'
    Copyright = '(c) 2020 Joakim Olsson. All rights reserved.'
    Description = 'The ShoutOut logger used in Caffeine and other ACG projects.'

    FunctionsToExport = @(
        "Clear-ShoutOutRedirect"
        "Get-ShoutOutConfig"
        "Get-ShoutOutDefaultLog"
        "Get-ShoutOUtRedirect"
        "Set-ShoutOutConfig"
        "Set-ShoutOutDefaultLog"
        "Set-ShoutOutRedirect"
        "ShoutOut"
    )

    CmdletsToExport = '*'
    VariablesToExport = '*'
    AliasesToExport = '*'
    PrivateData = @{

        PSData = @{

        }

    }
}