@(
    "Clear-ShoutOutRedirect"
    "Get-ShoutOutConfig"
    "Get-ShoutOutDefaultLog"
    "Get-ShoutOUtRedirect"
    "Set-ShoutOutConfig"
    "Set-ShoutOutDefaultLog"
    "Set-ShoutOutRedirect"
    "ShoutOut"
)